### ISSUE TITLE
Improve accept-marketplace-terms.yml playbook

### ISSUE THREAD

**Issue by cmendible** [cmendible/ansible.samples#1]
Hi @zikalino I'm opening this issue so, as discussed, we can improve the following [playbook](https://github.com/cmendible/ansible.samples/blob/master/azure/accept-marketplace-terms/accept-marketplace-terms.yml) which uses the new **azure_rm_resource** module to accept marketplace terms.

Thanks in advance!

**Comment by zikalino** [comment]
great! I will add it

**Comment by yungezz** [comment]
accept-term was supported in azure_rm_virtualmachine in 2.7 release https://github.com/ansible/ansible/commit/2541a8c494947b1ffe2e87993967fd82c6984463#diff-7deb317ec8158f70119f43a48d9ba545, you may want to have a try.

**Comment by cmendible** [comment]
Hi @yungezz great I'll try 2.7!!! But I also want to learn how to improve my calls with the REST module, as suggested by @zikalino, so I can create better playbooks in the future.

**Comment by cmendible** [comment]
Issue became stale so I'm closing it....
